CREATE TYPE ROLE AS ENUM (
    'STUDENT',
    'TEACHER',
    'ADMIN'
);

CREATE TYPE TEST_SESSION_STATUS AS ENUM (
    'STARTED',
    'DRAFT',
    'FINISHED'
);

CREATE TYPE QUESTION_TYPE AS ENUM (
    'CHOOSE',
    'MULTICHOOSE',
    'SORT',
    'MATCH',
    'SUBSTITUTION'
);

CREATE TYPE TEST_VARIANT_STATUS AS ENUM (
    'STARTED',
    'FINISHED'
);